# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 969da8021b7de82fb2011b1e330583fd0e1659a8ee2de5eda62572fc4ecb5068b0f10a87c859c3624e980f40a8b8eed273e982d398990ee2a8be046d28bfc3cf

test:
  secret_key_base: 2b5559bdca39c7b84ac0a18cd276d5ed8ff773e435e786274d732aeda6e498f107aa6f44f08d0090e562a3822a3f1cbb08fcf2cf8c7116261dd2087d8cd8cd2a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
